currency = "USD"
default_view = "favorites"
api = "coingecko"
colorscheme = "cointop"
refresh_rate = 60
cache_dir = "/tmp"

[shortcuts]
  "$" = "last_page"
  "%" = "sort_column_percent_holdings"
  "+" = "show_price_alert_add_menu"
  "/" = "open_search"
  0 = "first_page"
  1 = "sort_column_1h_change"
  2 = "sort_column_24h_change"
  3 = "sort_column_30d_change"
  7 = "sort_column_7d_change"
  "<" = "scroll_left"
  ">" = "scroll_right"
  "?" = "help"
  A = "toggle_price_alerts"
  C = ""
  E = ""
  F = "toggle_show_favorites"
  F1 = ""
  F5 = ""
  G = "move_to_page_last_row"
  H = "move_to_page_visible_first_row"
  L = "move_to_page_visible_last_row"
  M = "move_to_page_visible_middle_row"
  O = "open_link"
  P = "toggle_portfolio"
  Q = ""
  "[" = "previous_chart_range"
  "\\" = "toggle_table_fullscreen"
  "]" = "next_chart_range"
  a = "sort_column_available_supply"
  "alt+down" = "sort_column_desc"
  "alt+left" = "sort_left_column"
  "alt+right" = "sort_right_column"
  "alt+up" = "sort_column_asc"
  b = "sort_column_balance"
  c = "show_currency_convert_menu"
  "ctrl+C" = "quit"
  "ctrl+R" = "refresh"
  "ctrl+S" = "save"
  "ctrl+c" = "quit"
  "ctrl+d" = "page_down"
  "ctrl+f" = "toggle_favorite"
  "ctrl+j" = "enlarge_chart"
  "ctrl+k" = "shorten_chart"
  "ctrl+n" = "next_page"
  "ctrl+p" = "previous_page"
  "ctrl+r" = "refresh"
  "ctrl+s" = "save"
  "ctrl+u" = "page_up"
  down = ""
  e = "show_portfolio_edit_menu"
  end = ""
  enter = "toggle_row_chart"
  esc = ""
  f = ""
  g = "move_to_page_first_row"
  h = "previous_page"
  home = ""
  j = "move_down"
  k = "move_up"
  l = "next_page"
  left = ""
  m = "sort_column_market_cap"
  n = "sort_column_name"
  o = "open_link"
  p = "sort_column_price"
  pagedown = ""
  pageup = ""
  q = "quit_view"
  r = "sort_column_rank"
  right = ""
  s = "sort_column_symbol"
  space = ""
  t = "sort_column_total_supply"
  tab = "refresh"
  u = ""
  up = ""
  v = "sort_column_24h_volume"
  "{" = "first_chart_range"
  "}" = "last_chart_range"

[favorites]
  columns = ["name", "symbol", "price", "1h_change", "24h_change", "7d_change", "24h_volume", "market_cap", "total_supply", "available_supply", "last_updated"]
  names = ["Bitcoin", "Cardano", "Cosmos", "Dash", "Dogecoin", "Ethereum", "Monero", "Polkadot"]
  symbols = []

[portfolio]
  columns = ["rank", "name", "symbol", "price", "holdings", "balance", "1h_change", "24h_change", "7d_change", "percent_holdings", "last_updated"]
  holdings = [["Cardano", "400"]]

[price_alerts]
  alerts = []

[coinmarketcap]
  pro_api_key = ""

[table]
  columns = ["rank", "name", "symbol", "price", "1h_change", "24h_change", "7d_change", "24h_volume", "market_cap", "total_supply", "available_supply", "last_updated"]
